apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Note: namespace is created by Helm, not managed here
resources:
  - external-secret.yaml
  - cluster-issuer.yaml
  - wildcard-certificate.yaml
