apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bugsink
  namespace: bugsink
spec:
  ingressClassName: nginx
  rules:
  - host: bugsink.192.168.20.11.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bugsink
            port:
              number: 8000
